name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: npm install and test
        run: |
          npm install
          npm test --coverage
        env:
          CI: true
      - name: Codecov
        uses: codecov/codecov-action@v1.3.2
        with:
          directory: coverage
